{
    "name": "restaurant_pos_custom",
    "version": "1.0",
    "summary": "Custom Restaurant POS module with KDS and recipes",
    "description": "Lightweight Odoo module skeleton for Restaurant POS features (orders, recipes, KDS) with Arabic and French i18n",
    "author": "Generated by Copilot",
    "category": "Point of Sale",
    "depends": [
        "base",
        "point_of_sale",
        "stock"
    ],
    "data": [
        "views/restaurant_pos_views.xml",
        "views/kds_views.xml",
        "security/ir.model.access.csv"
    ],
    "qweb": [],
    "installable": true,
    "application": false
}
